Multipath support with non-zero length Connection IDs / explicit Path ID
refactoring to prepare multipath support without side effects

- packet number space map
- `PathEvent::Closed` now includes error code and reason
- function refactoring in lib.rs and frame.rs

This commit introduces the following features.

- Leave to the application to choose the multipath extensions or not
- Build on the `PathEvent`s to let the application decide which paths to use
- Provide default reasonable behavior into `quiche` while letting the
  application provide optimised behavior

== Requesting the Multipath feature

The application can request multipath through the `Config` structure using a
specific API,`set_multipath()`.
```rust
config.set_multipath(true);
```
The boolean value determines whether the underlying connection negotiates the
multipath extension. Once the handshake succeeded, the application can check
whether the connection has the multipath feature enabled using the
`is_multipath_enabled()` API on the `Connection` structure.

== Path management

The API requires the application to specify on which paths/4-tuples it wants
to send non-probing packets. Paths must first be validated before using them.
This is automatically done for servers, and client must use `probe_path()`.
Once the path is validated, the application decides whether it wants active
usage through the `set_active()` API. It provides a single API entrypoint to
request its usage or not. For active path usage, it can use the following.

```rust
if let Some(PathEvent::Validated(local, peer)) = conn.path_event_next() {
    conn.set_active(local, peer, true).unwrap();
}
```
Then, the path will then be considered to use non-probing packets.

On the other hand, if for some reason the application wants to temporarily
stop sending non-probing frames on a given path, it can do the following.

```rust
conn.set_active(local, peer, false).unwrap();
```
Note that in such state, quiche still replies to PATH_CHALLENGEs observed on
that path.

Finally, the multipath design allows a QUIC endpoint to close/abandon a
given path along with an error code and error message, without altering the
connection's operations as long as another path is available.

```rust
conn.abandon_path(local, peer, 42, "Some error message".into()).unwrap();
```

-- Retrocompatibility note

- The `Closed` variant of `PathEvent` is now a 4-tuple that, in addition to
the local and peer `SocketAddr`, also contains an `u64` error code and a
`Vec<u8>` reason message.
- There is a new variant of `PathEvent`: `PeerPathStatus` reports to the
application that the peer advertised some status for a given 4-tuple.
- There are two new `Error` variants: `UnavailablePath` and
`MultiPathViolation`.

-- Note

Currently this API is only available when multipath feature is enabled over
the session (i.e., `conn.is_multipath_enabled()` returns `true`). If the
extension is not enabled, `set_active()` and `abandon_path()` return an
`Error::InvalidState`. Actually, this API might sound "double usage" along
with the `migrate()` API (as there is no real "connection migration" with
multipath). Should we just keep the `set_active()` or similarly named API
and include the `migrate()` functionality in `set_active()`? Actually, an
client application without the multipath feature could just migrate using
`set_active(local, peer, true)`, setting the previous path in unused mode
under the hood.

== Scheduling sent packets

Similarly to the connection migration PR, there are two ways to control how
`quiche` schedules packets on paths.

The first consists in letting `quiche` handles this by itself. The
application simply uses the `send()` method. In the current master code,
`quiche` automatically handles path validation processing thanks to the
internal `get_send_path_id()` `Connection` method. The multipath patch
extends this method and iterates over all active paths following the lowest
latency path having its congestion window open heuristic (a reasonable
default in multipath protocols).

```rust
loop {
    let (write, send_info) = match conn.send(&mut out) {
            Ok(v) => v,

            Err(quiche::Error::Done) => break,

            Err(e) => {
                conn.close(false, 0x1, b"fail").ok();
                break;
            },
        };
        // write to socket bound to `send_info.from`
}
```

The second option is to let the application choose on which path it wants
to send the next packet. The application can iterate over the available paths
and their corresponding statistics using `path_stats()` and schedules packets
using `send_on_path()` method. This can be useful when the use case requires
some specific scheduling strategies. See `apps/src/client.rs` for an example
of such application-driven scheduling.

quiche-server: ensure burst sending on same path

apps: make the client's `A` flag less confusing

And fix clippy

apps: add warning if --max-active-cids is too low

clippy fixes

fix non-sending of ACK_MP when datagrams are enabled

Credits to @toshiiw for finding the issue.

fix comment

tests: support multipath in decode_pkt

Through the addition of the `find_scid_seq()` method on
`Connection`.

no need for public API `find_scid_seq()`

remove unused function since rebase

move support to draft-ietf-quic-multipath-04

add temporary simultaneous support of 04 and 05 drafts

also update applications to be able to run old multipath

add some additional flags for the multipath interop @ IETF117 hackathon

remove support for draft-ietf-quic-multipath-04

move support to draft-ietf-quic-multipath-06

apps: remove dangling --multipath-old flag

That was not doing much.

Make sure sending ACK_MP doesn't prevent bundling a ping when an ACK should be elicited

fully integrated explicit path ID

Change ACKMP to MPACK

As the draft will soon evolve with this.

support for draft -09/-10

remove legacy check which is no longer valid

remove another client-side legacy code from even path IDs

add CLI at quiche-client to retire DCIDs

fix receiving a PATH_ABANDON closing the path on which it came from

The path could not exist anymore, so close the path at the very end
when receiving a packet.

ffi: fix compilation errors

support for draft-11

do not enable app to abandon last active path

refactoring to make single-path works with recent FIPS changes

Move the next_pkt_num into the PathConnectionIdentifiers struct,
as each path should have its own single, monotonic sequence number.

multipath support for FIPS-aware BoringSSL library

/!\ Does not support OpenSSL yet

small clippy fix

minimal changes for draft-12

fix potential connection close if handshake not fully complete when
receiving a first ApplicationData packet

avoid raising InvalidState when acking more than one a PathAbandon

fix all_available_paths_backup behavior

The previous code was obviously wrong

cargo +nightly fmt

fix migration issue in multipath

When no PATH_ACK related to the migrated path is received before the
path validation of the new 4-tuple completes, the old path has no
opportunity to update its recovery and will never retransmit required
frames.

This is now solved by iterating on all network paths belonging to the
same path identifier.

move to draft-13

add missing API for OpenSSL

fix multipath test still based on even-only Path IDs

lib: avoid sending non-probing frames on potentially lost paths

If there is no explicit closure notification from the peer, the
previous behavior would lead to endless retransmissions on the failed
path, finally breaking the connection.

When facing such a PTO, the stack now tries to schedule such data on
different active paths, while ensuring that some ACK-eliciting
packets are still sent on the failed path.

lib: add reinject_all_on_pto parameter to the Config

This enables an endpoint to specify that it wants to retransmit all
the frames on PTO -- and not only the probing one. This is
especially useful in a multipath context, when a path silently failed.
Note, however, that this could lead to spurious retransmissions if the
path is still working -- hence the fact that this behavior is disabled
by default.

apps: add the --reinject-all-on-pto parameter

adding more tracing

fix migration issues

But there is a need for some refactoring here

Revert "adding more tracing"

This reverts commit 6776e31e2d1243e2cd9186e782a6417987add0c9.

fix possible bad interactions between active paths and multipath

path: only migrate recovery if path is validated

Otherwise, it would deadlock the path...

Introduce an explicit network path with the QUIC path

And provide a path-aware API for the application.

WIP2

WIP3

WIP

first compiling and test working version

move RttStats into NetworkPath

documentation update, clippy